### ISSUE TITLE
[Critical Error] when someone leave dj and no body is in waitlist

### ISSUE THREAD

**Issue by maxqui26** [goto-bus-stop/miniplug#34]
When the waitlist is empty and the last song is finish (or skip) : 
```c:\Users\Maxime\node_modules\miniplug\index.js:399
  waitlist.forEach((id) => {
          ^

TypeError: Cannot read property 'forEach' of undefined
    at wrapWaitlist (c:\Users\Maxime\node_modules\miniplug\index.js:399:11)
    at EventEmitter.ROLE.NONE [as wrapWaitlist] (c:\Users\Maxime\node_modules\miniplug\index.js:72:12)
    at onDjListUpdate (c:\Users\Maxime\node_modules\miniplug\index.js:855:32)
    at WebSocket.onAdvance (c:\Users\Maxime\node_modules\miniplug\index.js:860:7)
    at emitTwo (events.js:111:20)
    at WebSocket.emit (events.js:191:7)
    at c:\Users\Maxime\node_modules\plug-socket\index.js:24:10
    at Array.forEach (native)
    at WebSocket.onmessage (c:\Users\Maxime\node_modules\plug-socket\index.js:21:13)
    at WebSocket.onMessage (c:\Users\Maxime\node_modules\plug-socket\node_modules\ws\lib\EventTarget.js:103:16)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.EventEmitter.setSocket.head._receiver.onmessage (c:\Users\Maxime\node_modules\plug-socket\node_modules\ws\lib\WebSocket.js:146:54)
    at Receiver.dataMessage (c:\Users\Maxime\node_modules\plug-socket\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (c:\Users\Maxime\node_modules\plug-socket\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (c:\Users\Maxime\node_modules\plug-socket\node_modules\ws\lib\Receiver.js:165:16)
```
My .js
```const miniplug = require('miniplug');
const mp = miniplug({
    email: require('./bordel/auth.json').email,
    password: require('./bordel/auth.json').password
})
// Join a room 
mp.join('la-room-francaise').then((room) => {
    mp.chat(mp.me().username+' Online !');
})```

**Comment by goto-bus-stop** [comment]
Thanks for the report! This should be fixed in v1.6.2.
